// #Harij@1234!@#$
import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";



export const metadata: Metadata = {
  icons:"../logo.png",
  title: "Dashboard - UJS SHG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css"
        />
        
        <script src="https://kit.fontawesome.com/66aa7c98b3.js"></script>
      </Head>
      <body >{children}
      <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
           
      </body>

    </html>
  );
}















